[package]
name = "bayes_nets"
version = "0.1.0"
authors = ["Soubhik Ghosh <soub2111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.17.0"
rand = "0.7.2"
